Fix/issue video music upload
TERITORI/teritori-dapp pull request #1067
Opened 2024-03-07 10:46 UTC by sachin-into

Issues Fixed:
-fixes #1055 
-fixes #1053

2024-03-08 11:18 UTC, omniwired approved these changes
code is good, I didn't test it on a real device.

2024-03-11 09:00 UTC, omniwired submitted a review, later dismissed

2024-03-11 09:00 UTC, omniwired commented on packages/components/mini/SelectPicture.tsx
> +            opacity: Array.isArray(files) && files?.length > 0 ? 0.7 : 1,
✨

2024-03-19 01:20 UTC, n0izn0iz commented
fix conflicts pls

2024-03-19 14:10 UTC, n0izn0iz requested changes
I think this broke thumbnail upload for videos

2024-03-20 05:43 UTC, sachin-into commented
> I think this broke thumbnail upload for videos in web
here i have not changed video post creation just added UI for mobile app. i checked by commenting post creation function it did upload thumbnail image

2024-03-20 10:23 UTC, omniwired approved these changes

2024-03-21 17:48 UTC, n0izn0iz requested changes
music upload broken, it works on main but not on this branch
(pleas don't post test music on mainnet, use testnet for that, I can send you tokens if needed)

2024-03-22 08:53 UTC, sachin-into commented
> music upload broken, it works on main but not on this branch (pleas don't post test music on mainnet, use testnet for that, I can send you tokens if needed)

I uploaded music on web from this branch and it worked.
https://app.teritori.com/feed/post/testori-91b040be-4fc5-4f08-b8e5-233216d51af1

Can you specify, what is the problem?

2024-03-22 11:37 UTC, n0izn0iz approved these changes
seems problem is on my side

2024-03-22 12:03 UTC, merged