feat:added share and tip option on music list three dot button
TERITORI/teritori-dapp pull request #1080
Opened 2024-03-14 12:01 UTC by sachin-into

fixes #1052

<img width="404" alt="Screenshot 2024-03-14 at 5 42 55 PM" src="https://github.com/TERITORI/teritori-dapp/assets/154645503/adac705e-3ca1-4864-adbe-5f5ff08bb253">
<img width="992" alt="Screenshot 2024-03-14 at 5 42 36 PM" src="https://github.com/TERITORI/teritori-dapp/assets/154645503/94580c7e-5dad-4de7-8371-c3c1563503b8">

2024-03-15 07:34 UTC, omniwired submitted a review, later dismissed

2024-03-15 07:34 UTC, omniwired commented on packages/components/socialFeed/SocialActions/ShareButton.tsx
> +const WEBSITE_URL = "https://app.teritori.com";
This is ok in this case, as this will only be used in the mobile app.

2024-03-19 00:59 UTC, n0izn0iz requested changes
bug: the tip and share modal closes instantly after click on respective button in web

also I feel the ui is not great, maybe sync with konolee?
<img width="704" alt="Screenshot 2024-03-19 at 01 58 09" src="https://github.com/TERITORI/teritori-dapp/assets/7917064/193fa305-ce01-471a-ae3c-ba397920ee1f">

2024-03-19 06:12 UTC, sachin-into commented
changed UI to for now:
<img width="1633" alt="Screenshot 2024-03-19 at 11 55 43 AM" src="https://github.com/TERITORI/teritori-dapp/assets/154645503/f7127e35-1ba4-4d5c-8740-b4395c5d97ad">

2024-03-19 13:06 UTC, n0izn0iz approved these changes
LGTM

2024-03-19 13:50 UTC, omniwired approved these changes

2024-03-19 14:15 UTC, merged