feat(Mobile): normal mode hide unsupported apps (sidebar and dapp store) #1089
TERITORI/teritori-dapp pull request #1094
Opened 2024-03-15 09:48 UTC by omniwired

2024-03-19 01:12 UTC, n0izn0iz requested changes

2024-03-19 01:12 UTC, n0izn0iz commented on packages/screens/Mini/DAppStore/component/DAppsList.tsx
> +  const selectedApps = useSelector(selectCheckedApps) as pinnedAppsCollection;
don't break type safety please

2024-03-19 15:35 UTC, n0izn0iz approved these changes
LGTM

2024-03-21 07:53 UTC, sachin-into approved these changes

2024-03-21 17:35 UTC, merged