fix: share link url updated
TERITORI/teritori-dapp pull request #1127
Opened 2024-03-20 12:22 UTC by ChiragPansuriya-iView

2024-03-20 13:19 UTC, omniwired approved these changes

2024-03-20 13:44 UTC, WaDadidou approved these changes

2024-03-20 21:35 UTC, n0izn0iz requested changes
like I said, there is a medium refactor needed, ShareButton should take the network-prefixed-postid as prop, using the selected network is not reliable, and will break when we will have cross-chain feed, also the `#Teritori` anchor is very weird

2024-03-22 08:46 UTC, omniwired approved these changes

2024-03-26 01:27 UTC, n0izn0iz requested changes
See https://github.com/TERITORI/teritori-dapp/blob/main/CONTRIBUTING.md#multi-networks-multi-chains

2024-03-29 15:26 UTC, closed without merging