Feat: Add endpoint to check if an user is member of a dao
TERITORI/teritori-dapp pull request #1302
Opened 2024-10-12 03:31 UTC by WaDadidou

2024-10-12 07:10 UTC, Villaquiranm approved these changes

2024-10-12 07:26 UTC, n0izn0iz requested changes

2024-10-12 07:26 UTC, n0izn0iz commented on api/dao/v1/dao.proto
> +    string dao_address = 3;
```suggestion
    string user_id = 1;
    string dao_id = 2;
```

2024-10-12 18:58 UTC, omarsy approved these changes

2024-10-12 21:16 UTC, WaDadidou commented on api/dao/v1/dao.proto
> +    string dao_address = 3;
Agree ! I was not sure

2024-10-13 17:06 UTC, n0izn0iz requested changes
unless you need to save an error for later use, naming all errors `err` is idiomatic go

2024-10-13 17:06 UTC, n0izn0iz commented on go/pkg/dao/dao_service.go
> +	daoNetwork, daoAddress, parseDaoIdErr := s.conf.NetStore.ParseUserID(daoId)
```suggestion
	daoNetwork, daoAddress, err := s.conf.NetStore.ParseUserID(daoId)
```

2024-10-13 17:06 UTC, n0izn0iz commented on go/pkg/dao/dao_service.go
> +	_, userAddress, parseUSerIdErr := s.conf.NetStore.ParseUserID(userId)
```suggestion
	_, userAddress, err := s.conf.NetStore.ParseUserID(userId)
```

2024-10-14 16:11 UTC, n0izn0iz approved these changes

2024-10-14 16:49 UTC, omarsy approved these changes

2024-10-14 17:04 UTC, merged