test: e2e dao deployer
TERITORI/teritori-dapp pull request #1304
Opened 2024-10-14 11:01 UTC by MikaelVallenet

WIP

---------------------------

Blocked by error: 

```js
await adena.DoContract({
  messages: [
    {
      type: "/vm.m_addpkg",
      value: {
        creator: "g16jv3rpz7mkt0gqulxas56se2js7v5vmc6n6e0r",
        deposit: "1ugnot",
        package: {
          Name: "helloworld",
          Path: "gno.land/r/teritori/helloworld",
          Files: [
            {
              Name: "helloworld.gno",
              Body: "package helloworld\n  func main() string {\n\treturn \"Hello, World!\"\n}"
            }
          ]
        }
      }
    }
  ],
  gasFee: 1,
  gasWanted: 20000000
});

output: {status: 'failure', data: null, code: 4001, message: 'Adena could not execute the transaction.', type: 'TRANSACTION_FAILED'}
```

2024-10-14 16:15 UTC, n0izn0iz requested changes

2024-10-14 16:15 UTC, n0izn0iz commented on cypress/e2e/dao-creation.cy.ts
> +    ).click();
don't use those hyper-specific selectors please, add a testId if needed instead

2024-10-15 18:04 UTC, Villaquiranm commented on packages/utils/gno.ts
> +  console.log(JSON.stringify(req));
To remove ?

2024-10-15 18:04 UTC, Villaquiranm commented on packages/context/WalletsProvider/gnotest/index.tsx
>            throw new Error("Unsupported message type: " + msg.type);
Maybe create a constant for `/vm.m_call` and  `/vm.m_addpkg`
on utils/gno.ts ?

2024-10-18 18:39 UTC, n0izn0iz commented
this could be a good time to move dao related fields from `GnoNetworkInfo` type to a new `NetworkFeature` `GnoDAOs` type but we can do it in another PR

2024-10-21 00:00 UTC, n0izn0iz commented on packages/utils/gnodao/deploy.ts
> +		},
normal daos don't need to (and can't) control the tori coin, it's only in the demo dao

2024-10-31 17:22 UTC, n0izn0iz requested changes

2024-10-31 17:22 UTC, n0izn0iz commented on packages/utils/gnodao/deploy.ts
> +    "${network.toriPkgPath}"
leftover

2024-11-02 15:12 UTC, n0izn0iz approved these changes
good for a first step towards stabilizing dao feature

2024-11-02 15:42 UTC, merged