fix: Handle Gno network switch modal
TERITORI/teritori-dapp pull request #1424
Opened 2024-11-26 12:54 UTC by hthieu1110

Fix issue: https://github.com/TERITORI/teritori-dapp/issues/1380

2024-11-26 13:07 UTC, n0izn0iz requested changes
Looks good, except there is a weird behavior when you connect for the first time (when the app is not authorized yet) and you are on the wrong gno network (for example, adena is on test5 and the app is on portal loop)

<img width="536" alt="Screenshot 2024-11-26 at 14 06 49" src="https://github.com/user-attachments/assets/d522b36c-9223-4b32-826b-a8d276ee89db">

2024-11-26 17:15 UTC, n0izn0iz requested changes
still have the same behavior, please read the previous comment carefully to reproduce

2024-11-26 19:04 UTC, WaDadidou commented
### I have this: 
![image](https://github.com/user-attachments/assets/ecfff41e-4062-4e23-a4e8-d74d62ceb8a0)

### When I click Connect, I have an infinite loading:
![image](https://github.com/user-attachments/assets/5f59d5b0-825f-491b-8abc-9d6f0677899b)

### When I close the wallet window, I got this error : 
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'chainId')`

Same on deploy-preview-1424--gno-dapp et deploy-preview-1424--teritori-dapp

2024-11-27 06:36 UTC, hthieu1110 commented
> Same on deploy-preview-1424--gno-dapp et deploy-preview-1424--teritori-dapp:
> 
> ### I have this:
> ![image](https://private-user-images.githubusercontent.com/50441633/390107917-ecfff41e-4062-4e23-a4e8-d74d62ceb8a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODkzODQsIm5iZiI6MTczMjY4OTA4NCwicGF0aCI6Ii81MDQ0MTYzMy8zOTAxMDc5MTctZWNmZmY0MWUtNDA2Mi00ZTIzLWE0ZTgtZDc0ZDYyY2ViOGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA2MzEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZTAwOTlmYzdhNWYwNjE3Yjc5OTYxMjExMDM1MmNhNjI1MTBmZDFmODljZWE0MDE3NTFkODQ2ZTBiOTgxYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jCkJDb07TItkJS1m4f3RQ6qUqyQuDzwmjpiXyBM86Bs)
> 
> ### When I click Connect, I have an infinite loading:
> ![image](https://private-user-images.githubusercontent.com/50441633/390108044-5f59d5b0-825f-491b-8abc-9d6f0677899b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODkzODQsIm5iZiI6MTczMjY4OTA4NCwicGF0aCI6Ii81MDQ0MTYzMy8zOTAxMDgwNDQtNWY1OWQ1YjAtODI1Zi00OTFiLThhYmMtOWQ2ZjA2Nzc4OTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA2MzEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZTQ1Yzk3YTMxYzcyYzViZDM0YjQzYmFhMmQ3OTkyMGEzMDU0NmMxYjhlMWUwMjk2ZTMxYWE1MDcyMjZjMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PC8sHwvSWkGahNVobpBrrEJLBaETeqHUwVxTFq12XPk)
> 
> ### When I close the wallet window, I got this error :
> `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'chainId')`

I'm not able to reproduce this. Step I've tried:
- Open the dapp with unauthorized wallet
- Select Gno Test 5 while in Adena it's Portal loop
- Connect with Adena
=> it shows only the error that Norman mentioned above

2024-11-27 06:55 UTC, hthieu1110 commented
> still have the same behavior, please read the previous comment carefully to reproduce
> 
> you need to remove the authorization in this list to reproduce
> 
> <img alt="Screenshot 2024-11-26 at 18 15 46" width="372" src="https://private-user-images.githubusercontent.com/7917064/390073879-754710df-6114-405a-a4e9-983d595c69ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODkzODQsIm5iZiI6MTczMjY4OTA4NCwicGF0aCI6Ii83OTE3MDY0LzM5MDA3Mzg3OS03NTQ3MTBkZi02MTE0LTQwNWEtYTRlOS05ODNkNTk1YzY5YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjdUMDYzMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmUxYjNlZDllMjEzNmYwNjJkZjA2MmQ5ZTQyZDZkMzUxNzhiODkxNWJjMmY3YTExYjAzOWI3N2FlYzE0YmRlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ZErV2jX55JH4l_zQ5yABexZfDjxoi2h4CJYIXp7a31I">

Okie, I've push the fix and cover some other edge-cases also.

2024-11-28 01:23 UTC, hthieu1110 commented
> @hthieu1110 I got this error when the Adena Switch modal is open, BUT I click on "Connect Wallet" then "Adena Wallet"
> 
> ![image](https://github.com/user-attachments/assets/94f34f25-a8d8-4224-8856-cc3b4fb4ca91)
> 
> I think we should alway show the loader in ConnectWalletButton when a wallet window in open, to prevent the user from breaking the UI if he doesn't interact with the wallet extension.
> 
> ![image](https://github.com/user-attachments/assets/99498b1e-49a0-4763-893d-b71519153e0c)
> 
> 
> 
> Maybe out of scope
> 
> 
> 
> 

IMHO, it's a discussion in another scope, for now, when the switch modal is open, you ask to connect to another Adena network so it's normal that it fetches the connected network from your wallet and thus close the modal. That behaviour is not really related to this Pr.

2024-11-28 01:37 UTC, n0izn0iz commented
actually @WaDadidou is right, this is why we were calling `getAccount` in the button handler

but fixing this issue is more important than the problem of introducing this regression so we can merge as-is and open another issue IMO

2024-11-28 01:44 UTC, n0izn0iz requested changes
Following the same flow as before (first connection, wrong network):
if you cancel the "switch network" request in adena, the "Connect wallet" button then does nothing

2024-11-28 01:45 UTC, n0izn0iz commented
I recommend you try testing in "adversarial mode", thinking about way to break the flow before asking for new reviews

2024-11-28 02:04 UTC, hthieu1110 commented
> I recommend you try testing in "adversarial mode", thinking about way to break the flow before asking for new reviews

Of course testing all the flow possible on my side is what I have done firstly before asking the review. I've tested all the cases that I think about and there are edge cases that I dont even know

2024-11-28 17:18 UTC, WaDadidou commented
Empty app's local data
Wallet: Portal Loop
https://deploy-preview-1424--gno-dapp.netlify.app/orgs

![image](https://github.com/user-attachments/assets/de4efe9b-52be-46bd-9ba2-16893c3e5d8c)

==> I got empty netowrks list, even after Click connect, then connect adena
![image](https://github.com/user-attachments/assets/4955a0f0-0b89-45d2-bdf9-011503e30d27)
![image](https://github.com/user-attachments/assets/24be7f20-4555-4c8d-a078-811bebc0d77e)

2024-11-28 17:29 UTC, WaDadidou commented
- Empty app's local data
- Wallet: Portal Loop
- Cancel the Switch from Adena modal
https://deploy-preview-1424--gno-dapp.netlify.app/feed

![image](https://github.com/user-attachments/assets/de4efe9b-52be-46bd-9ba2-16893c3e5d8c)

==> I got the expected error
![image](https://github.com/user-attachments/assets/40502b44-7183-46c0-9174-b85d5c0afbff)

2024-11-29 13:46 UTC, n0izn0iz requested changes
Now the same flow I described just doesn't try to change network in adena
This can result in the following for pages where there is only one valid gno network for the page like a [post details page](https://deploy-preview-1424--gno-dapp.netlify.app/user/gnotest5-g199v9fxazlp2n7ls7n4e04x0q4rcg3ggehtjdsh)

<img width="1321" alt="Screenshot 2024-11-29 at 14 45 14" src="https://github.com/user-attachments/assets/e2d2b78f-a585-456f-9972-58a9e970cd3e">

2024-12-02 20:17 UTC, WaDadidou commented
I'm a little bit lost with the flows to tests, I'm testing following the changes and report I I find something. And report the expected cases to make them clear.
But it looks good, I didn't get issue.

I saw this expected case:
![image](https://github.com/user-attachments/assets/e5315472-9d4d-4c5e-ab44-ec54b354fdeb)

2024-12-02 20:59 UTC, WaDadidou commented
### I had some weird behaviors:
- "The account is already connected to this website" if I:
   - Lock Adena wallet
   - Refresh the page (And got "Adena is locked")
   - Click Connect Wallet on Teritori, Click on Adena Wallet on the modal on Teritori
- "Switching to the network has been rejected by the user" if I:
   - Click Connect Wallet from Teritori instead of Switch Network from Adena modal
   
### We must lock the Connect Wallet button' by disabling the button and/or showing a loader or a button text "Look at ur Adena extension plz". Weird behaviors could be prevent


https://github.com/user-attachments/assets/444e8986-0d1e-496c-bd89-a580a60e8bb9

### Random tests, not really important, just got a weid behavior at the end, but I due to all side effects I guess

https://github.com/user-attachments/assets/887dc853-398b-4020-b380-cd974154aa05

2024-12-06 08:28 UTC, n0izn0iz commented
I get a `Adena is locked` error toast without any interaction on my side when I navigate to the site

2024-12-06 17:05 UTC, WaDadidou commented
> I get a `Adena is locked` error toast without any interaction on my side when I navigate to the site

You should have this state on your Adena wallet, is it the case ?

![image](https://github.com/user-attachments/assets/7c0ebbac-817c-4b8e-b4e0-5bca7729dcea)

2024-12-06 18:45 UTC, n0izn0iz requested changes

2024-12-06 18:45 UTC, n0izn0iz commented on packages/context/WalletsProvider/adena/index.ts
> +      dispatch: any,
don't use any for this

2024-12-08 13:36 UTC, hthieu1110 commented on packages/context/WalletsProvider/adena/index.ts
> +      dispatch: any,
Fixed

2024-12-08 14:03 UTC, n0izn0iz commented
aussi, en vertu de l'article 49 alinéa 3 de la constitution, j'engage la responsabilité de mon organisation décentralisée sur l'application de la requête de fusionnement numéro 1424

2024-12-08 14:03 UTC, merged