feat(gno/orgs): save & display kind of organizations
TERITORI/teritori-dapp pull request #1469
Opened 2024-12-30 15:20 UTC by MikaelVallenet

an organization could be based on different kinds:
- roles
- memberships
- tokens
- ...

This information should be saved into contracts & retrievable to be able to adapt business logic depending on the kind of the org.

The PR scope is to save it and display it in UPP

2025-01-02 10:48 UTC, n0izn0iz requested changes

2025-01-02 10:48 UTC, n0izn0iz commented on gno/r/dao_realm/dao_realm.gno
> +	dao_registry.Register(func() dao_interfaces.IDAOCore { return daoCore }, "DAO Realm", "Default testing DAO", "memberships based organization", "https://images.unsplash.com/photo-1477959858617-67f85c
The registry should only be mapping from realm pkgpath to IDAOCore, the additional fields were there when the profile realm didn't exist but they should be removed actually, this is a review mistake by me when we moved to profile realm for daos

I think we should handle the "dao kind" by inspecting the dao voting module, which already has a `.Info()` api

2025-01-02 14:57 UTC, MikaelVallenet commented on gno/r/dao_realm/dao_realm.gno
> +	dao_registry.Register(func() dao_interfaces.IDAOCore { return daoCore }, "DAO Realm", "Default testing DAO", "memberships based organization", "https://images.unsplash.com/photo-1477959858617-67f85c
So when listing (for the screens w/ all daos) should i fetch profile realm (name, bio & avatar) for each field of each DAO ?

I did what you suggest to handle the dao kind by inspecting the dao voting module using the Info().String() endpoint

2025-01-02 18:46 UTC, n0izn0iz commented on gno/r/dao_realm/dao_realm.gno
> +	dao_registry.Register(func() dao_interfaces.IDAOCore { return daoCore }, "DAO Realm", "Default testing DAO", "memberships based organization", "https://images.unsplash.com/photo-1477959858617-67f85c
there is two option there:
- query the profile realm in the registry list function and enrich the response within gno
- use the useUserInfo hook like we do for users, it already supports gno dao if I'm not mistaken

2025-01-02 22:54 UTC, n0izn0iz approved these changes
LGTM

2025-01-03 00:26 UTC, WaDadidou approved these changes
LGTM :)

2025-01-03 00:55 UTC, merged