fix: add Select Input and update inputs style
TERITORI/teritori-dapp pull request #647
Opened 2023-07-24 23:57 UTC by WaDadidou

![image](https://github.com/TERITORI/teritori-dapp/assets/50441633/1eb40399-acf5-4e58-b966-60c0d551b81c)
![image](https://github.com/TERITORI/teritori-dapp/assets/50441633/c0f2596e-68a7-44d0-9bcc-8b2e9118c64c)
![image](https://github.com/TERITORI/teritori-dapp/assets/50441633/b2e21d8b-c708-4036-a714-002854829d9a)
![image](https://github.com/TERITORI/teritori-dapp/assets/50441633/774a1772-950a-4dcb-b7bd-2fce5601e6ea)

2023-07-25 08:24 UTC, omniwired requested changes

2023-07-25 12:15 UTC, WaDadidou commented on packages/components/inputs/TextInputCustom.tsx
> +    color: neutral77, //TODO: neutralA3 by default here ?
Done yes

2023-08-03 14:43 UTC, omniwired approved these changes

2023-08-03 14:59 UTC, zxxma commented
LGTM

2023-08-03 14:59 UTC, merged