feat: leap wallet integration
TERITORI/teritori-dapp pull request #679
Opened 2023-08-29 04:28 UTC by omniwired

2023-08-31 13:04 UTC, WaDadidou requested changes

2023-08-31 13:07 UTC, omniwired commented on packages/components/connectWallet/ConnectLeapButton.tsx
> +      const leap = window.leap;
It's inside a try catch block.
I want to to fail of not present.

2023-09-01 08:04 UTC, hthieu1110 approved these changes

2023-09-01 08:18 UTC, WaDadidou approved these changes

2023-09-06 04:40 UTC, merged