WIP: fix all unused exports from packages/components
TERITORI/teritori-dapp pull request #700
Opened 2023-09-12 15:32 UTC by clegirar

2023-09-21 12:05 UTC, WaDadidou commented
Could you rename `RiotGameScreen.web.tsx` as `RiotGameScreen.tsx` since this file is removed ? https://github.com/TERITORI/teritori-dapp/blob/ce0d7ea427b993e0dc4f1c8a8006bb821933d445/packages/screens/RiotGame/RiotGameScreen.tsx
(And change the import in `Navigator.tsx`)

2023-09-21 12:12 UTC, WaDadidou commented
In https://github.com/TERITORI/teritori-dapp/blob/68f8f691930c3a669e9cc037392694edacfdce30/packages/components/socialFeed/SocialActions/ShareButton.tsx#L10, could you rename `FeedPostShareModalProps` as `ShareButtonProps` (Or remove this interface, cause there is only one property), since this file is removed: https://github.com/TERITORI/teritori-dapp/blob/ce0d7ea427b993e0dc4f1c8a8006bb821933d445/packages/components/socialFeed/SocialActions/FeedPostShareModal.tsx

2023-09-21 12:18 UTC, WaDadidou commented
Please fix lint-and-build and update the branch with origin/main

2023-09-21 12:18 UTC, WaDadidou requested changes

2023-09-22 07:18 UTC, clegirar commented on packages/screens/DAppStore/apps/toripunks/query/useHistoryData.ts
Oh yeah you right 👍

2023-09-22 07:18 UTC, clegirar commented on packages/screens/DAppStore/apps/toripunks/query/userHistoryMock.ts
Yes you right

2023-09-22 07:19 UTC, clegirar commented on packages/components/gradientText/index.ts
Which tool give you this error ? Because i have nothing that say that ?

2023-09-22 07:22 UTC, clegirar commented
If it's possible i want to rebase on main after merging Audio Player to have just one nightmare to resolve conflicts 🙃

2023-09-24 13:54 UTC, omniwired submitted a review, later dismissed

2023-09-24 14:43 UTC, omniwired commented on packages/components/gradientText/index.ts
it was happening when trying to build the project

2023-09-28 15:58 UTC, merged