Fix/omnifixes
TERITORI/teritori-dapp pull request #704
Opened 2023-09-14 06:37 UTC by omniwired

2023-10-05 10:04 UTC, omniwired commented
> This commit makes the `GovernanceScreen` layout wrong, wdyt ? => [9ef0332](https://github.com/TERITORI/teritori-dapp/commit/9ef0332cefe58fc6564d5192044ba2638145b20b)
> 
> ![image](https://user-images.githubusercontent.com/50441633/271038971-7fb18133-8552-4847-ac57-6d8bd7409f3f.png)

updated with better styles

2023-10-05 11:34 UTC, WaDadidou requested changes

2023-10-06 03:10 UTC, hthieu1110 commented on packages/components/ScreenContainer/index.tsx
> +  if (!onBackPress) {
IMHO we should not overide props. Suggestion:
```
const doBackPress = () => {
    onBackPress && navigation.canGoBack() && navigation.goBack();
}
```

2023-10-06 03:10 UTC, hthieu1110 commented on packages/components/TopMenu/TopMenuMyTeritories.tsx
> +        <>
no need <>

2023-10-06 03:12 UTC, hthieu1110 commented on packages/screens/Governance/GovernanceDetails.tsx
> +              fontSize: 20,
Can we use : fontSemibold20 ?

2023-10-06 03:13 UTC, hthieu1110 commented on packages/screens/Governance/GovernanceDetails.tsx
> +              fontSize: 20,
can we use fontSemibold20 ?

2023-10-06 03:13 UTC, hthieu1110 commented on packages/screens/Governance/GovernanceDetails.tsx
> +                fontSize: 14,
can we use fontSemibold14 or fontMedium14 ?

2023-10-06 03:14 UTC, hthieu1110 commented on packages/screens/Governance/GovernanceDetails.tsx
> +                backgroundColor: "#333333",
there is : neutral33 for this

2023-10-06 08:54 UTC, hthieu1110 submitted a review, later dismissed
LGTM

2023-10-06 11:01 UTC, n0izn0iz requested changes

2023-10-09 06:37 UTC, omniwired commented on packages/components/footers/Footer.tsx
> -const FooterGetUp: React.FC = () => {
yes

2023-10-09 07:16 UTC, omniwired commented on packages/screens/Marketplace/CollectionScreen.tsx
> -      onBackPress={() => navigation.navigate("Marketplace")}
fixed

2023-10-09 07:16 UTC, omniwired commented on packages/screens/Stake/StakeScreen.tsx
> +      onBackPress={() => navigation.goBack()}
reverted

2023-11-15 04:58 UTC, closed without merging