Bridge UI WIP
TERITORI/teritori-dapp pull request #754
Opened 2023-11-17 06:29 UTC by dubiella

2023-11-29 06:00 UTC, omniwired commented
@dubiella please send the latest code you have here.
cc: @hthieu1110

2023-11-29 06:01 UTC, omniwired requested changes

2023-11-29 06:01 UTC, omniwired commented on packages/screens/RiotGame/RiotGameBridgeScreen.tsx
> +const styles = StyleSheet.create({
this won't pass CI/CD.
Just inline the styles if that makes sense.

2024-02-10 22:59 UTC, n0izn0iz commented
done in #483

2024-02-10 22:59 UTC, closed without merging