feat: Premium admin setup design added
TERITORI/teritori-dapp pull request #937
Opened 2024-02-08 11:11 UTC by ChiragPansuriya-iView

Premium Admin Setup design 
![Screenshot 2024-02-08 at 4 40 12 PM](https://github.com/TERITORI/teritori-dapp/assets/134677881/bd41215a-c3a9-4d77-b8ee-b4f2c6c20fe8)
![Screenshot 2024-02-08 at 4 40 33 PM](https://github.com/TERITORI/teritori-dapp/assets/134677881/e206822b-53b0-45b1-8b04-9fed9f8d59d5)

2024-02-08 11:55 UTC, ChiragPansuriya-iView commented
FYI ,
Tier name looks like that in Figma, but I made different. I am working on matching the Figma.
![Screenshot 2024-02-08 at 5 22 54 PM](https://github.com/TERITORI/teritori-dapp/assets/134677881/d441ef2b-80c7-4f96-af28-b742cc98aac5)

2024-02-08 13:19 UTC, clegirar requested changes
It's a really good practice to add specific `TextInputs`, really like it 👍 BUT, we have to minimize the number of variants of it 👍 Can you check if other components already used can be fit with your behavior (sometime it can be a design issue) ?

Second point found some components/files a little too long, `SubscriptionSetupModal.tsx`, `AccordionComponent.tsx` and the `.web.tsx` file. Can you do something to make it more readable 👍

2024-02-08 13:19 UTC, clegirar commented on packages/screens/UserPublicProfile/components/accordion/AccordionComponent.tsx
> +          <Image
Please use `OptimizedImage` instead 👍

2024-02-08 13:19 UTC, clegirar commented on packages/components/hub/ProfileButton.tsx
> +          size="M"
This change didn't create any regression on other components that use it ?
If you don't know please take care of that 👍

2024-02-08 13:43 UTC, clegirar commented
<img width="1129" alt="Screenshot 2024-02-08 at 14 33 22" src="https://github.com/TERITORI/teritori-dapp/assets/33428384/572a6778-3a82-4059-848b-887af2d12d52">
<img width="475" alt="Screenshot 2024-02-08 at 14 33 50" src="https://github.com/TERITORI/teritori-dapp/assets/33428384/5a05fcd3-c995-4a93-8fa4-71434da8706e">

The first one, the text is on 2 lines, and we want it in 1 line 👍 (relating to the figma)
The second one is just to reask you about that https://github.com/TERITORI/teritori-dapp/pull/937#issuecomment-1933960897

2024-02-09 14:20 UTC, clegirar commented
For UI stuff:
![image](https://github.com/TERITORI/teritori-dapp/assets/33428384/141bc042-b334-4f1a-b880-e4fb184906b1)

The text and the arrow are not correctly aligned, and i think the start is a little too on top

And the premium sub text is not on one line again

2024-02-11 21:26 UTC, merged