feat: allow edit profile directly on the user profile
TERITORI/teritori-dapp pull request #957
Opened 2024-02-14 08:10 UTC by VishalRakholiya-iView

2024-02-14 09:08 UTC, omniwired approved these changes

2024-02-14 09:48 UTC, clegirar requested changes

2024-02-14 09:48 UTC, clegirar commented on packages/utils/navigation.ts
> +    isEditProfile?: boolean;
Why you add this but you didn't use it in the screen ?
Please remove it if you don't use it

2024-02-14 09:48 UTC, clegirar commented on packages/screens/UserPublicProfile/tabScreens/PostsUPPScreen.tsx
> +// import { TNSUpdateNameScreen } from "@/screens/TeritoriNameService/TNSUpdateNameScreen";
Useless comment here, you can delete it too

2024-02-15 09:53 UTC, clegirar approved these changes
LGTM 👍

2024-02-15 10:21 UTC, merged