Fix/mini navigation
TERITORI/teritori-dapp pull request #960
Opened 2024-02-14 10:24 UTC by sachin-into

1. moved normal navigation and mini navigation under same stack navigation
2. fixed dApps onPress navigation
3. added chat\feed\wallets button at bottom of dApps screen

2024-02-15 04:28 UTC, omniwired approved these changes

2024-02-15 11:07 UTC, n0izn0iz requested changes

2024-02-15 11:07 UTC, n0izn0iz commented on packages/components/navigation/MiniModeNavigator.tsx
> +export const MiniModeNavigator = () => {
```suggestion
export const getMiniModeScreens = () => {
```

2024-02-15 11:07 UTC, n0izn0iz commented on packages/components/navigation/MiniModeNavigator.tsx
> +export const MiniModeNavigator = () => {
the other name is confusing as the capitalized names are used for components and this is not a component but rather a function that returns jsx, also it's not a navigator anymore

2024-02-21 08:33 UTC, omniwired approved these changes

2024-02-21 11:32 UTC, merged