Feat : Toast component for mini mode
TERITORI/teritori-dapp pull request #987
Opened 2024-02-22 09:41 UTC by sachin-into

2024-02-22 21:43 UTC, n0izn0iz requested changes
we already have this kind of systems in useFeedback, please adapt it instead of having two providers and api for feedback

2024-02-23 02:00 UTC, omniwired reviewed
looks good, I agree with @n0izn0iz about useFeedback

2024-02-23 15:37 UTC, n0izn0iz requested changes

2024-02-26 04:09 UTC, sachin-into commented on packages/context/FeedbacksProvider.tsx
> +  setMiniToast: () => {},
mini toast has 4 different status and 2 different variant style so I created new api without touching previous working  apis. Previous toast works as it used to and new api is for mini mode won't that be simple and easier to distinguish

<img width="697" alt="image" src="https://github.com/TERITORI/teritori-dapp/assets/154645503/7a1ce24c-1b0f-41db-9c2e-50ddeff7cf1b">

2024-02-26 20:12 UTC, n0izn0iz commented on packages/context/FeedbacksProvider.tsx
> +  setMiniToast: () => {},
I don't think, a toast should be a toast, the mode can affect how it renders but we should have a single api

you can extend the current api

2024-02-28 11:21 UTC, n0izn0iz requested changes

2024-02-28 11:21 UTC, n0izn0iz commented on packages/components/toasts/NormalToast.tsx
> +export const NormalToast: React.FC<NormalToastProps> = ({
there is a regression in this component, on main it has an icon

<img width="449" alt="Screenshot 2024-02-28 at 12 20 47" src="https://github.com/TERITORI/teritori-dapp/assets/7917064/7e715533-d435-4571-b3d0-cc3b19cfa026">

on this pr the `!` icon does not appear

2024-02-29 10:53 UTC, n0izn0iz requested changes
regression in padding
this pr:
<img width="453" alt="Screenshot 2024-02-29 at 11 51 26" src="https://github.com/TERITORI/teritori-dapp/assets/7917064/9b20ba06-f077-4412-872e-bda29045057c">
main:
<img width="447" alt="Screenshot 2024-02-29 at 11 53 34" src="https://github.com/TERITORI/teritori-dapp/assets/7917064/f5b60320-90f2-4f3e-ab6e-bfe51556f09c">

2024-02-29 15:20 UTC, n0izn0iz approved these changes
LGTM :)

2024-02-29 15:20 UTC, merged