feat: added governance proposal details page
TERITORI/teritori-dapp pull request #994
Opened 2024-02-23 12:10 UTC by ChiragPansuriya-iView

design updates as per figma 
![Screenshot 2024-02-23 at 5 40 14 PM](https://github.com/TERITORI/teritori-dapp/assets/134677881/bb7772a8-d695-4b3f-8717-4cdedd960ca3)

2024-02-29 11:43 UTC, clegirar requested changes
Just little things to fix 👍 
Ill check the design this afternoon

2024-02-29 11:43 UTC, clegirar commented on packages/hooks/governance/useProposal.ts
The `useProposal` and `useProposals` can be confusing i think, just one letter differ from each other, so maybe `useGetProposal` and `useGetAllProposals` can be better ? It's a proposition (im not sure about the `Get` in it, but it means that you fetch a data)

2024-02-29 11:43 UTC, clegirar commented on packages/screens/Governance/GovernanceProposal/GovernanceVoteHeader/components/VoteTimeDetailsBox.tsx
> +        </View>
This component cannot be extract ? I think that is the same pattern below no ? If yes extract it and the file will be easier to read too. I think this little component can stay in the file

2024-02-29 11:46 UTC, ChiragPansuriya-iView commented on packages/hooks/governance/useProposal.ts
noted

2024-02-29 13:49 UTC, omniwired commented
Mobile styles need some love.
![image](https://github.com/TERITORI/teritori-dapp/assets/322761/1176bb3a-43b1-42b9-9f16-0af2f3ff8a44)

2024-02-29 13:49 UTC, omniwired requested changes
mobile styles

2024-03-04 22:21 UTC, n0izn0iz requested changes

2024-03-04 22:21 UTC, n0izn0iz commented on packages/screens/Governance/GovernanceProposal/GovernanceProposalScreen.tsx
> +  }, [id, selectedNetworkId]);
use react-query for queries please

2024-03-04 22:21 UTC, n0izn0iz commented on packages/screens/Governance/GovernanceScreen.tsx
> +  }, [selectedNetworkId]);
react-query

2024-03-13 10:47 UTC, clegirar commented
![image](https://github.com/TERITORI/teritori-dapp/assets/33428384/91012af2-09fd-48aa-8315-c0a9a6f64bab)

Just i have this behavior on mobile, on web, maybe you can make sure that the search input and `All states` button in one line.
And the `Reviews` text and the separator are overlapped, just fix that too

2024-03-15 16:37 UTC, merged